### ISSUE TITLE
小程序接入极验后捕获到报错

### ISSUE THREAD

**Issue by shinelp100** [GeeTeam/gt4-miniapp-demo#1]
"MiniProgramError Cannot read property ＇left＇ of undefined TypeError: Cannot read property ＇left＇ of undefined at n.initTrack (https://usr/package/loginPackage/appservice.app.js:1180:52190) at n._touchstart (https://usr/package/***/appservice.app.js:1180:50643) at Object.i.safeCallback (https://lib/WASubContext.js:1:445597) at https://lib/WASubContext.js:1:638755 at J (https://lib/WASubContext.js:1:529515) at https://lib/WASubContext.js:1:530064"

**Comment by shinelp100** [comment]
你们代码中存在initTrack吗
